package io.opentelemetry.javaagent.instrumentation.spark;

import java.text.NumberFormat;

public class ApplicationId {

  public static final String appIdStrPrefix = "application_";
  private final long clusterTimestamp;
  private final int id;

  ApplicationId(long clusterTimestamp, int id) {
    this.clusterTimestamp = clusterTimestamp;
    this.id = id;
  }

  public static ApplicationId newInstance(long clusterTimestamp, int id) {
    return new ApplicationId(clusterTimestamp, id);
  }

  public int getId() {
    return id;
  }

  public long getClusterTimestamp() {
    return clusterTimestamp;
  }

  static final ThreadLocal<NumberFormat> appIdFormat =
      new ThreadLocal<NumberFormat>() {
        @Override
        public NumberFormat initialValue() {
          NumberFormat fmt = NumberFormat.getInstance();
          fmt.setGroupingUsed(false);
          fmt.setMinimumIntegerDigits(4);
          return fmt;
        }
      };

  @Override
  public String toString() {
    return appIdStrPrefix + this.getClusterTimestamp() + "_" + appIdFormat.get().format(getId());
  }

  @Override
  public int hashCode() {
    // Generated by eclipse.
    final int prime = 371237;
    int result = 6521;
    long clusterTimestamp = getClusterTimestamp();
    result = prime * result + (int) (clusterTimestamp ^ (clusterTimestamp >>> 32));
    result = prime * result + getId();
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    ApplicationId other = (ApplicationId) obj;
    if (this.getClusterTimestamp() != other.getClusterTimestamp()) return false;
    if (this.getId() != other.getId()) return false;
    return true;
  }
}
